services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      tags:
        - "thomastwyman557/rp_flask_board"
    ports:
      - 80:8000

    # Docker Compose automatically looks for '.env' files at the root of the project - or adjacent to the Compose file itself.
    # It's a best practice to exclude any '.env' files from source control / git.
    # Be sure to add your own .env file(s) to ensure proper application functionality.
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DATABASE: ${FLASK_DATABASE}

    # Docker Compose Watch allows for real-time updates to your code, and 
    # will either synchronize ('sync'), or rebuild ('rebuild') your project, depending on how you ask Compose to behave.
    # use 'docker compose up --watch' to start your app in 'watch' mode
    develop:
      watch:
        - action: sync
          path: ./board/static
          target: /app/static
        - action: rebuild
          path: ./board/templates
          target: /board/templates
        - action: rebuild
          path: ./board/requirements.txt

